services:
  server:
    container_name: backend
    build:
      context: .
      dockerfile: ./server/Dockerfile
      target: development
    ports:
      - '3000:3000'
    volumes:
      - ./server/src:/app/server/src
    environment:
      - NODE_ENV=development
    command: npm --workspace server run dev
    restart: unless-stopped

  client:
    container_name: frontend
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: development
    ports:
      - '4000:4000'
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    environment:
      - VITE_NODE_ENV=development
    command: npm --workspace client run dev --port 4000
    restart: unless-stopped

  client-prod:
    container_name: production
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: runner
    ports:
      - '80:80'
    environment:
      - VITE_NODE_ENV=production
    restart: always